import os
import logging
import asyncio

from fastapi import FastAPI, Request, HTTPException
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters,
                    )
from google import genai
from google.genai import types

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("voxly")

BOT_TOKEN = os.environ["BOT_TOKEN"]
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET", "voxly-secret")
RENDER_EXTERNAL_URL = os.environ.get("RENDER_EXTERNAL_URL")

app = FastAPI()

                    telegram_app = Application.builder().token(BOT_TOKEN).build()
                    gemini = genai.Client(api_key=GEMINI_API_KEY)


                    async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
                        keyboard = [
                                [
                                            InlineKeyboardButton("📝 Transcribe", callback_data="transcribe"),
                                                        InlineKeyboardButton("🧠 Summarize", callback_data="summarize"),
                                                                ],
                                                                        [
                                                                                    InlineKeyboardButton("🌍 Translate", callback_data="translate"),
                                                                                                InlineKeyboardButton("✍️ Reply", callback_data="reply"),
                                                                                                        ],
                                                                                                            ]

                                                                                                                await update.message.reply_text(
                                                                                                                        "🎙️ Voxly AI hazırdır!\n\n"
                                                                                                                                "Mənə səsli mesaj göndər. Mən onu yazıya çevirəcəyəm.",
                                                                                                                                        reply_markup=InlineKeyboardMarkup(keyboard),
                                                                                                                                            )


                                                                                                                                            async def voice_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                msg = update.message

                                                                                                                                                    await msg.reply_text("🎧 Səsi qəbul etdim. Bir az gözlə...")

                                                                                                                                                        voice = msg.voice
                                                                                                                                                            tg_file = await context.bot.get_file(voice.file_id)
                                                                                                                                                                data = await tg_file.download_as_bytearray()

                                                                                                                                                                    prompt = (
                                                                                                                                                                            "Transcribe this Telegram voice message accurately. "
                                                                                                                                                                                    "Return ONLY the transcript. "
                                                                                                                                                                                            "Keep the original language and wording as much as possible. "
                                                                                                                                                                                                    "If the speaker is speaking Azerbaijani, always write Azerbaijani "
                                                                                                                                                                                                            "using the Azerbaijani Latin alphabet (Azərbaycan əlifbası). "
                                                                                                                                                                                                                    "Use these letters when appropriate: ə, ı, ö, ü, ş, ç, ğ. "
                                                                                                                                                                                                                            "Do not write Azerbaijani in Arabic script."
                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                            response = await asyncio.to_thread(
                                                                                                                                                                                                                                                        gemini.models.generate_content,
                                                                                                                                                                                                                                                                   import os
                                                                                                                                                                                                                                                                   import logging
                                                                                                                                                                                                                                                                   import asyncio

                                                                                                                                                                                                                                                                   from fastapi import FastAPI, Request, HTTPException
                                                                                                                                                                                                                                                                   from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
                                                                                                                                                                                                                                                                   from telegram.ext import (
                                                                                                                                                                                                                                                                       Application,
                                                                                                                                                                                                                                                                           CommandHandler,
                                                                                                                                                                                                                                                                               MessageHandler,
                                                                                                                                                                                                                                                                                   ContextTypes,
                                                                                                                                                                                                                                                                                       filters,
                                                                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                                                                       from google import genai
                                                                                                                                                                                                                                                                                       from google.genai import types

                                                                                                                                                                                                                                                                                       logging.basicConfig(level=logging.INFO)
                                                                                                                                                                                                                                                                                       logger = logging.getLogger("voxly")

                                                                                                                                                                                                                                                                                       BOT_TOKEN = os.environ["BOT_TOKEN"]
                                                                                                                                                                                                                                                                                       GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
                                                                                                                                                                                                                                                                                       WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET", "voxly-secret")
                                                                                                                                                                                                                                                                                       RENDER_EXTERNAL_URL = os.environ.get("RENDER_EXTERNAL_URL")

                                                                                                                                                                                                                                                                                       app = FastAPI()

                                                                                                                                                                                                                                                                                       telegram_app = Application.builder().token(BOT_TOKEN).build()
                                                                                                                                                                                                                                                                                       gemini = genai.Client(api_key=GEMINI_API_KEY)


                                                                                                                                                                                                                                                                                       async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                           keyboard = [
                                                                                                                                                                                                                                                                                                   [
                                                                                                                                                                                                                                                                                                               InlineKeyboardButton("📝 Transcribe", callback_data="transcribe"),
                                                                                                                                                                                                                                                                                                                           InlineKeyboardButton("🧠 Summarize", callback_data="summarize"),
                                                                                                                                                                                                                                                                                                                                   ],
                                                                                                                                                                                                                                                                                                                                           [
                                                                                                                                                                                                                                                                                                                                                       InlineKeyboardButton("🌍 Translate", callback_data="translate"),
                                                                                                                                                                                                                                                                                                                                                                   InlineKeyboardButton("✍️ Reply", callback_data="reply"),
                                                                                                                                                                                                                                                                                                                                                                           ],
                                                                                                                                                                                                                                                                                                                                                                               ]

                                                                                                                                                                                                                                                                                                                                                                                   await update.message.reply_text(
                                                                                                                                                                                                                                                                                                                                                                                           "🎙️ Voxly AI hazırdır!\n\n"
                                                                                                                                                                                                                                                                                                                                                                                                   "Mənə səsli mesaj göndər. Mən onu yazıya çevirəcəyəm.",
                                                                                                                                                                                                                                                                                                                                                                                                           reply_markup=InlineKeyboardMarkup(keyboard),
                                                                                                                                                                                                                                                                                                                                                                                                               )


                                                                                                                                                                                                                                                                                                                                                                                                               async def voice_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                                                                                                                                   msg = update.message

                                                                                                                                                                                                                                                                                                                                                                                                                       await msg.reply_text("🎧 Səsi qəbul etdim. Bir az gözlə...")

                                                                                                                                                                                                                                                                                                                                                                                                                           voice = msg.voice
                                                                                                                                                                                                                                                                                                                                                                                                                               tg_file = await context.bot.get_file(voice.file_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                   data = await tg_file.download_as_bytearray()

                                                                                                                                                                                                                                                                                                                                                                                                                                       prompt = (
                                                                                                                                                                                                                                                                                                                                                                                                                                               "Transcribe this Telegram voice message accurately. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                       "Return ONLY the transcript. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Keep the original language and wording as much as possible. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "If the speaker is speaking Azerbaijani, always write Azerbaijani "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "using the Azerbaijani Latin alphabet (Azərbaycan əlifbası). "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "Use these letters when appropriate: ə, ı, ö, ü, ş, ç, ğ. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Do not write Azerbaijani in Arabic script."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               response = await asyncio.to_thread(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           gemini.models.generate_content,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

